version: '3.8'
services:
 # api:
 #   container_name: stone_container
 #   env_file:
 #     - '.env'
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   ports:
 #     - 3000:3000
 #   networks:
 #     - nesjs-network
 #   restart: unless-stopped
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
      
networks:
  nesjs-network:
volumes:
  redis_data: